#!/usr/bin/env python3
"""
LLM-powered Template Transformer using Azure OpenAI GPT-4
Converts Dropbox Sign template JSON to DocuSign template creation payload
"""

import os
import sys
import json
import base64
from pathlib import Path
from typing import Dict, Any, Optional
from dotenv import load_dotenv

# Import Azure OpenAI
try:
    from openai import AzureOpenAI
except ImportError:
    print("Error: openai package not installed. Run: pip install openai")
    sys.exit(1)

# Import DocuSign auth manager
from src.auth_manager import DocuSignAuthManager

# Load environment variables
load_dotenv()

class LLMTemplateTransformer:
    """Transform Dropbox Sign templates to DocuSign using Azure OpenAI GPT-4"""
    
    def fix_coordinates(self, payload: Dict[str, Any], template_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Fix coordinates from HelloSign OLD system (80 DPI) to DocuSign (72 DPI)
        
        Args:
            payload: The DocuSign payload generated by LLM
            template_data: The original HelloSign template data
            
        Returns:
            Payload with fixed coordinates
        """
        # DPI conversion factor: 72/80 = 0.9
        DPI_SCALE = 0.9
        
        # X-coordinate offset in HelloSign OLD system (portrait pages start at 100)
        X_OFFSET = 100
        
        # DocuSign special Y-offsets for signature/initial tabs
        SIGN_Y_OFFSET = 21
        INITIAL_Y_OFFSET = 16
        
        # Page height at 80 DPI for US Letter (11 inches)
        PAGE_HEIGHT_80DPI = 880
        
        # Fix coordinates in recipients tabs
        if "recipients" in payload and "signers" in payload["recipients"]:
            for signer in payload["recipients"]["signers"]:
                if "tabs" in signer:
                    for tab_type, tabs in signer["tabs"].items():
                        if isinstance(tabs, list):
                            for tab in tabs:
                                # Get tab label for logging
                                tab_label = tab.get("tabLabel", "Unknown")
                                
                                # Get original x and y
                                if "xPosition" in tab:
                                    x_original = float(tab["xPosition"])
                                    # Apply transformation: subtract offset, then scale
                                    x_new = (x_original - X_OFFSET) * DPI_SCALE
                                    x_final = int(round(x_new))
                                    tab["xPosition"] = str(x_final)
                                    print(f"  📍 {tab_label} X: {x_original} → {x_final} (removed offset {X_OFFSET}, scaled by {DPI_SCALE})")
                                
                                if "yPosition" in tab:
                                    y_original = float(tab["yPosition"])
                                    
                                    # For multi-page documents, find which page we're on
                                    page_num = int(y_original // PAGE_HEIGHT_80DPI) + 1
                                    y_on_page = y_original % PAGE_HEIGHT_80DPI
                                    
                                    # Apply DPI scaling
                                    y_new = y_on_page * DPI_SCALE
                                    
                                    # Apply DocuSign special offsets based on tab type
                                    offset_applied = 0
                                    if tab_type == "signHereTabs":
                                        y_new -= SIGN_Y_OFFSET
                                        offset_applied = SIGN_Y_OFFSET
                                    elif tab_type == "initialHereTabs":
                                        y_new -= INITIAL_Y_OFFSET
                                        offset_applied = INITIAL_Y_OFFSET
                                    
                                    # Round to nearest integer
                                    y_final = int(round(y_new))
                                    tab["yPosition"] = str(y_final)
                                    
                                    if page_num > 1:
                                        print(f"  📍 {tab_label} Y: {y_original} → {y_final} (page {page_num}, y_on_page={y_on_page}, offset={offset_applied})")
                                    else:
                                        print(f"  📍 {tab_label} Y: {y_original} → {y_final} (scaled by {DPI_SCALE}, offset={offset_applied})")
                                    
                                    # Update page number if not already set
                                    if "pageNumber" not in tab or tab["pageNumber"] == "1":
                                        tab["pageNumber"] = str(page_num)
                                
                                # Fix width and height if present
                                if "width" in tab:
                                    w_original = float(tab["width"])
                                    w_new = w_original * DPI_SCALE
                                    tab["width"] = str(int(round(w_new)))
                                
                                if "height" in tab:
                                    h_original = float(tab["height"])
                                    h_new = h_original * DPI_SCALE
                                    tab["height"] = str(int(round(h_new)))
        
        return payload
    
    def __init__(self, init_docusign=False):
        """Initialize the transformer with Azure OpenAI client
        
        Args:
            init_docusign: If True, initialize DocuSign auth manager (only needed for API calls)
        """
        # Initialize Azure OpenAI client - EXACTLY like your working example
        from openai import AzureOpenAI
        
        self.client = AzureOpenAI(
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            api_version="2024-10-21",
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT")
        )
        
        # Store deployment name for later use
        self.deployment = "gpt-4o"  # Using the model name directly as in your example
        
        # Only initialize DocuSign auth manager if needed (for actual API calls)
        self.auth_manager = None
        if init_docusign:
            from config.config import INTEGRATION_KEY, USER_ID, PRIVATE_KEY, BASE_URI, ACCOUNT_ID
            self.auth_manager = DocuSignAuthManager(
                integration_key=INTEGRATION_KEY,
                user_id=USER_ID,
                private_key=PRIVATE_KEY,
                base_uri=BASE_URI
            )
        
    def create_system_prompt(self) -> str:
        """Create a comprehensive system prompt for the LLM"""
        return """You are an expert at converting Dropbox Sign (HelloSign) template JSON to DocuSign template creation payloads.

## Your Task
Convert the provided Dropbox Sign template JSON into a valid DocuSign Templates API payload that can be used with the POST /v2.1/accounts/{accountId}/templates endpoint.

## Key Transformation Rules

### 1. Template Metadata
- Map `title` → `envelopeTemplateDefinition.name`
- Map `template_id` → `envelopeTemplateDefinition.description` (as reference)
- Generate appropriate `emailSubject` and `emailBlurb`

### 2. Documents
- Create a document object with:
  - `documentId`: "1" (or increment for multiple docs)
  - `name`: From Dropbox Sign document name
  - `documentBase64`: Will be provided separately
  - `fileExtension`: Extract from document name

### 3. Recipients
- Map `signer_roles` to `recipients.signers` array
- Each signer needs:
  - `roleName`: From Dropbox Sign role name
  - `recipientId`: String number starting from "1"
  - `routingOrder`: String number (usually "1" unless specified)

### 4. Form Fields to Tabs Mapping
Critical mappings from Dropbox Sign field types to DocuSign tab types:

| Dropbox Sign Type | DocuSign Tab Type | Tab Array Name |
|------------------|-------------------|----------------|
| signature | signHereTabs | signHereTabs |
| initials | initialHereTabs | initialHereTabs |
| text | textTabs | textTabs |
| date | dateTabs | dateTabs |
| checkbox | checkboxTabs | checkboxTabs |
| dropdown | listTabs | listTabs |
| radio | radioGroupTabs | radioGroupTabs |

### 5. Coordinate Transformation
- Just copy the coordinates as-is, we'll fix them programmatically later
- Map coordinates:
  - `x` → `xPosition` (copy value and convert to string)
  - `y` → `yPosition` (copy value and convert to string)
  - `width` → `width` (copy value, optional for some tabs)
  - `height` → `height` (copy value, optional for some tabs)

### 6. Field Properties
- Map `name` → `tabLabel`
- Map `required` → `required` (as string "true"/"false")
- Map `signer` (number) → match to `recipientId`
- Always set `documentId`: "1" (or match to document)
- Always set `pageNumber`: "1" (unless specified otherwise)

### 7. Special Considerations
- Group radio buttons by their group name
- Handle conditional fields if present
- Preserve validation patterns where applicable
- Map font properties if specified

## Output Format
Return ONLY valid JSON that can be directly used with the DocuSign Templates API.
The structure should follow the DocuSign template creation schema exactly.
Note : Not all fields are needed you just return based on waht is needeed as per repsonse from Dropboxsign api response
## Example Structure
```json
{
    "name": "Example Template",
    "description": "Migrated from Dropbox Sign",
    "shared": "false",
    "emailSubject": "Please sign this document",
    "status": "created",
    "documents": [
        {
            "documentBase64": "JVBERi0xLjQKJeLj...",
            "documentId": "1",
            "fileExtension": "pdf",
            "name": "Contract.pdf"
        }
    ],
    "recipients": {
        "signers": [
            {
                "recipientId": "1",
                "roleName": "signer",
                "routingOrder": "1",
                "tabs": {
                    "signHereTabs": [
                        {
                            "documentId": "1",
                            "pageNumber": "1",
                            "xPosition": "100",
                            "yPosition": "200"
                        }
                    ],
                    "textTabs": [
                        {
                            "documentId": "1",
                            "pageNumber": "1",
                            "xPosition": "150",
                            "yPosition": "250",
                            "width": 100,
                            "height": 20,
                            "tabLabel": "name",
                            "required": "true"
                        }
                    ]
                }
            }
        ],
        "carbonCopies": []
    }
}
```

## Important Notes
1. Ensure all string values are properly quoted
2. Convert all numeric positions to strings
3. Use "true"/"false" as strings for boolean values
4. Include only non-empty tab arrays
5. Validate recipientId matches between signers and tabs
6. The documentBase64 will be replaced with actual base64 data - use "{{BASE64_PLACEHOLDER}}" as placeholder

Remember: The output must be valid JSON that DocuSign API will accept directly."""

    def create_user_prompt(self, dropbox_json: Dict[str, Any], pdf_base64: str) -> str:
        """Create the user prompt with the Dropbox Sign template data"""
        return f"""Convert this Dropbox Sign template to DocuSign format:

```json
{json.dumps(dropbox_json, indent=2)}
```

The document PDF has been converted to base64. Replace {{{{BASE64_PLACEHOLDER}}}} with the actual base64 string in your response.

Generate a complete DocuSign template creation payload following all the transformation rules."""

    def transform_template(self, dropbox_json: Dict[str, Any], pdf_base64: str) -> Dict[str, Any]:
        """
        Transform Dropbox Sign template to DocuSign format using LLM
        
        Args:
            dropbox_json: Dropbox Sign template API response
            pdf_base64: Base64 encoded PDF document
            
        Returns:
            DocuSign template creation payload
        """
        try:
            print("🤖 Calling Azure OpenAI GPT-4 for template transformation...")
            
            # Create the prompts
            system_prompt = self.create_system_prompt()
            user_prompt = self.create_user_prompt(dropbox_json, pdf_base64)
            
            # Call Azure OpenAI
            response = self.client.chat.completions.create(
                model=self.deployment,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.1,  # Low temperature for consistent, deterministic output
                max_tokens=4000
            )
            
            # Extract the response
            llm_response = response.choices[0].message.content
            
            # Clean up the response (remove markdown if present)
            if "```json" in llm_response:
                llm_response = llm_response.split("```json")[1].split("```")[0]
            elif "```" in llm_response:
                llm_response = llm_response.split("```")[1].split("```")[0]
            
            # Parse the JSON response
            docusign_payload = json.loads(llm_response.strip())
            
            # Replace the placeholder with actual base64
            if "documents" in docusign_payload:
                for doc in docusign_payload["documents"]:
                    if "documentBase64" in doc and "{{BASE64_PLACEHOLDER}}" in doc["documentBase64"]:
                        doc["documentBase64"] = pdf_base64
            
            # Fix coordinates from HelloSign OLD system (80 DPI) to DocuSign (72 DPI)
            print("🔧 Fixing coordinates from HelloSign (80 DPI) to DocuSign (72 DPI)...")
            docusign_payload = self.fix_coordinates(docusign_payload, dropbox_json)
            
            print("✅ LLM transformation and coordinate fix completed successfully")
            return docusign_payload
            
        except json.JSONDecodeError as e:
            print(f"❌ Error parsing LLM response as JSON: {e}")
            print(f"LLM Response: {llm_response[:500]}...")
            raise
        except Exception as e:
            print(f"❌ Error during LLM transformation: {e}")
            raise
    
    def validate_payload(self, payload: Dict[str, Any]) -> bool:
        """
        Validate the generated DocuSign payload
        
        Args:
            payload: DocuSign template creation payload
            
        Returns:
            True if valid, raises exception otherwise
        """
        # Check required top-level fields
        if "envelopeTemplateDefinition" not in payload:
            raise ValueError("Missing envelopeTemplateDefinition")
        
        if "documents" not in payload or not payload["documents"]:
            raise ValueError("Missing or empty documents array")
        
        if "recipients" not in payload:
            raise ValueError("Missing recipients")
        
        # Check document has base64
        for doc in payload["documents"]:
            if "documentBase64" not in doc or not doc["documentBase64"]:
                raise ValueError(f"Document {doc.get('name', 'unknown')} missing base64 data")
        
        # Check recipients have tabs
        if "signers" in payload["recipients"]:
            for signer in payload["recipients"]["signers"]:
                if "tabs" not in signer:
                    print(f"⚠️ Warning: Signer {signer.get('roleName', 'unknown')} has no tabs")
        
        return True
    
    def create_template_in_docusign(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create the template in DocuSign using the API
        
        Args:
            payload: DocuSign template creation payload
            
        Returns:
            API response with template details
        """
        try:
            if not self.auth_manager:
                raise ValueError("DocuSign auth manager not initialized. Initialize with init_docusign=True to create templates in DocuSign.")
            
            # Get access token
            access_token = self.auth_manager.get_access_token()
            account_id = self.auth_manager.get_account_id()
            
            # Validate payload
            self.validate_payload(payload)
            
            # Create template via API
            import requests
            
            url = f"{self.auth_manager.base_path}/v2.1/accounts/{account_id}/templates"
            headers = {
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
            
            print(f"📤 Creating template in DocuSign...")
            response = requests.post(url, json=payload, headers=headers)
            
            if response.status_code == 201:
                result = response.json()
                print(f"✅ Template created successfully!")
                print(f"   Template ID: {result.get('templateId')}")
                print(f"   Template Name: {result.get('name')}")
                return result
            else:
                print(f"❌ Failed to create template: {response.status_code}")
                print(f"   Error: {response.text}")
                raise Exception(f"DocuSign API error: {response.text}")
                
        except Exception as e:
            print(f"❌ Error creating template in DocuSign: {e}")
            raise
    
    def migrate_template(self, template_id: str, templates_dir: str = "templates/dropbox_sign") -> Dict[str, Any]:
        """
        Complete migration flow: read files, transform, and create in DocuSign
        
        Args:
            template_id: Dropbox Sign template ID
            templates_dir: Directory containing downloaded templates
            
        Returns:
            DocuSign API response
        """
        try:
            # Find template directory
            template_dir = None
            for dir_name in os.listdir(templates_dir):
                if template_id in dir_name:
                    template_dir = os.path.join(templates_dir, dir_name)
                    break
            
            if not template_dir or not os.path.exists(template_dir):
                raise FileNotFoundError(f"Template directory not found for ID: {template_id}")
            
            print(f"📁 Found template directory: {template_dir}")
            
            # Read the Dropbox Sign JSON
            json_file = os.path.join(template_dir, "dropbox_api_response.json")
            if not os.path.exists(json_file):
                raise FileNotFoundError(f"JSON file not found: {json_file}")
            
            with open(json_file, 'r') as f:
                dropbox_json = json.load(f)
            
            # Find and read the PDF file
            pdf_file = None
            for file in os.listdir(template_dir):
                if file.endswith('.pdf'):
                    pdf_file = os.path.join(template_dir, file)
                    break
            
            if not pdf_file:
                raise FileNotFoundError(f"PDF file not found in {template_dir}")
            
            print(f"📄 Reading PDF: {os.path.basename(pdf_file)}")
            with open(pdf_file, 'rb') as f:
                pdf_base64 = base64.b64encode(f.read()).decode('utf-8')
            
            # Transform using LLM
            docusign_payload = self.transform_template(dropbox_json, pdf_base64)
            
            # Save the transformed payload for debugging
            transformed_file = os.path.join(template_dir, "docusign_payload.json")
            with open(transformed_file, 'w') as f:
                json.dump(docusign_payload, f, indent=2)
            print(f"💾 Saved transformed payload to: {transformed_file}")
            
            # Create template in DocuSign
            result = self.create_template_in_docusign(docusign_payload)
            
            # Save the result
            result_file = os.path.join(template_dir, "docusign_result.json")
            with open(result_file, 'w') as f:
                json.dump(result, f, indent=2)
            print(f"💾 Saved DocuSign result to: {result_file}")
            
            return result
            
        except Exception as e:
            print(f"❌ Migration failed: {e}")
            raise


def main():
    """Test the LLM transformer with a sample template"""
    try:
        # Check for .env file
        if not os.path.exists('.env'):
            print("❌ Error: .env file not found")
            print("Please create a .env file with:")
            print("  AZURE_OPENAI_ENDPOINT=your-endpoint")
            print("  AZURE_OPENAI_API_KEY=your-api-key")
            print("  AZURE_OPENAI_DEPLOYMENT_NAME=your-deployment")
            print("  DOCUSIGN_INTEGRATION_KEY=your-key")
            print("  DOCUSIGN_USER_ID=your-user-id")
            print("  DOCUSIGN_ACCOUNT_ID=your-account-id")
            print("  DOCUSIGN_PRIVATE_KEY_PATH=your-key-path")
            return
        
        # Initialize transformer
        transformer = LLMTemplateTransformer()
        
        # Check if we have a template ID as argument
        if len(sys.argv) > 1:
            template_id = sys.argv[1]
            print(f"🚀 Migrating template: {template_id}")
            result = transformer.migrate_template(template_id)
            print("✅ Migration completed successfully!")
        else:
            # Test with the sample template if it exists
            sample_id = "0931d9d4ec3c6dec4bc26de0975dd412d846e939"
            templates_dir = "templates/dropbox_sign"
            
            # Check if sample exists
            sample_found = False
            if os.path.exists(templates_dir):
                for dir_name in os.listdir(templates_dir):
                    if sample_id in dir_name:
                        sample_found = True
                        break
            
            if sample_found:
                print(f"🚀 Testing with sample template: {sample_id}")
                result = transformer.migrate_template(sample_id)
                print("✅ Test completed successfully!")
            else:
                print("ℹ️ Usage: python llm_transformer.py [template_id]")
                print("   No template ID provided and no sample template found.")
                print("   Please download a template first using the web UI.")
    
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main() 